export const navConfig = {
  AboutMe: {
    glass: "AboutMeGlass",
    text: "AboutMe_Red_Bloom",
    target: "PhoneFacePlateScreen_White",
    cameraOffset: [-1.5, 0, 0],
    htmlRotation: [0, -Math.PI / 2, 0],
    distanceFactor: 0.4,
    htmlSizeAxis: ["z", "x"],
    htmlOffset: [-0.001, 0, 0],
  },
  Projects: {
    glass: "ProjectsGlass",
    text: "Projects_Red_Bloom",
    target: "VendingMachineBodyScreen_White",
    cameraOffset: [0, 0, 1],
    htmlRotation: [0, 0, 0],
    distanceFactor: 0.4,
    htmlSizeAxis: ["x", "y"],
    htmlOffset: [0, 0, 0.001],
  },
  Games: {
    glass: "GamesGlass",
    text: "Games_Red_Bloom",
    target: "ArcadeMachineBodyScreen_White",
    cameraOffset: [0, 0, -1.2],
    htmlRotation: [0, Math.PI, 0],
    distanceFactor: 0.4,
    htmlSizeAxis: ["x", "y"],
    htmlOffset: [0, 0, -0.001],
  },
  Music: {
    glass: "MusicGlass",
    text: "Music_Red_Bloom",
    target: "JackboxBodyScreen_White",
    cameraOffset: [0, 0, -1.2],
    htmlRotation: [0, Math.PI, 0],
    distanceFactor: 0.4,
    htmlSizeAxis: ["x", "y"],
    htmlOffset: [0, 0, -0.001],
  },
  Contact: {
    glass: "ContactGlass",
    text: "Contact_Red_Bloom",
    target: "PhoneFacePlateScreen_White",
    cameraOffset: [-1.5, 0, 0],
    htmlRotation: [0, Math.PI / 2, 0],
    distanceFactor: 0.4,
    htmlSizeAxis: ["z", "x"],
    htmlOffset: [-0.001, 0, 0],
  },
};
